with-expecter: true
packages:
  go.lumeweb.com/portal-middleware/auth:
    interfaces:
      UserChecker:
        config:
          filename: "user_checker_mock.go"
      TokenValidator:
        config:
          filename: "token_validator_mock.go"
      ConfigProvider:
        config:
          filename: "config_provider_mock.go"
      APIProvider:
        config:
          filename: "api_provider_mock.go"
      CookieSetter:
        config:
          filename: "cookie_setter_mock.go"
disable-version-string: true
issue-845-fix: true
resolve-type-alias: false