template: testify
template-data:
  unroll-variadic: true
filename: "mock_{{.InterfaceName}}.go"
dir: '{{.InterfaceDir}}'
packages:
  go.lumeweb.com/portal-middleware/auth:
    interfaces:
      AccessChecker: {}
      UserChecker: {}
  go.lumeweb.com/portal-middleware/auth/adapter:
    interfaces:
      APIProvider: {}
      ConfigProvider: {}
      CookieSetter: {}
  go.lumeweb.com/portal-middleware/auth/validation:
    interfaces:
      TokenValidator: {}
