// Code generated by mockery. DO NOT EDIT.

package auth

import mock "github.com/stretchr/testify/mock"

// MockAccessChecker is an autogenerated mock type for the AccessChecker type
type MockAccessChecker struct {
	mock.Mock
}

type MockAccessChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccessChecker) EXPECT() *MockAccessChecker_Expecter {
	return &MockAccessChecker_Expecter{mock: &_m.Mock}
}

// CheckAccess provides a mock function with given fields: userID, host, path, method
func (_m *MockAccessChecker) CheckAccess(userID uint, host string, path string, method string) (bool, error) {
	ret := _m.Called(userID, host, path, method)

	if len(ret) == 0 {
		panic("no return value specified for CheckAccess")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, string, string, string) (bool, error)); ok {
		return rf(userID, host, path, method)
	}
	if rf, ok := ret.Get(0).(func(uint, string, string, string) bool); ok {
		r0 = rf(userID, host, path, method)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(uint, string, string, string) error); ok {
		r1 = rf(userID, host, path, method)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccessChecker_CheckAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckAccess'
type MockAccessChecker_CheckAccess_Call struct {
	*mock.Call
}

// CheckAccess is a helper method to define mock.On call
//   - userID uint
//   - host string
//   - path string
//   - method string
func (_e *MockAccessChecker_Expecter) CheckAccess(userID interface{}, host interface{}, path interface{}, method interface{}) *MockAccessChecker_CheckAccess_Call {
	return &MockAccessChecker_CheckAccess_Call{Call: _e.mock.On("CheckAccess", userID, host, path, method)}
}

func (_c *MockAccessChecker_CheckAccess_Call) Run(run func(userID uint, host string, path string, method string)) *MockAccessChecker_CheckAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockAccessChecker_CheckAccess_Call) Return(_a0 bool, _a1 error) *MockAccessChecker_CheckAccess_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccessChecker_CheckAccess_Call) RunAndReturn(run func(uint, string, string, string) (bool, error)) *MockAccessChecker_CheckAccess_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccessChecker creates a new instance of MockAccessChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccessChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccessChecker {
	mock := &MockAccessChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
