// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserChecker creates a new instance of MockUserChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserChecker {
	mock := &MockUserChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserChecker is an autogenerated mock type for the UserChecker type
type MockUserChecker struct {
	mock.Mock
}

type MockUserChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserChecker) EXPECT() *MockUserChecker_Expecter {
	return &MockUserChecker_Expecter{mock: &_m.Mock}
}

// AccountExists provides a mock function for the type MockUserChecker
func (_mock *MockUserChecker) AccountExists(ctx context.Context, userID uint) (bool, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for AccountExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (bool, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) bool); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserChecker_AccountExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AccountExists'
type MockUserChecker_AccountExists_Call struct {
	*mock.Call
}

// AccountExists is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockUserChecker_Expecter) AccountExists(ctx interface{}, userID interface{}) *MockUserChecker_AccountExists_Call {
	return &MockUserChecker_AccountExists_Call{Call: _e.mock.On("AccountExists", ctx, userID)}
}

func (_c *MockUserChecker_AccountExists_Call) Run(run func(ctx context.Context, userID uint)) *MockUserChecker_AccountExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserChecker_AccountExists_Call) Return(b bool, err error) *MockUserChecker_AccountExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockUserChecker_AccountExists_Call) RunAndReturn(run func(ctx context.Context, userID uint) (bool, error)) *MockUserChecker_AccountExists_Call {
	_c.Call.Return(run)
	return _c
}

// IsAccountVerified provides a mock function for the type MockUserChecker
func (_mock *MockUserChecker) IsAccountVerified(ctx context.Context, userID uint) (bool, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsAccountVerified")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (bool, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) bool); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserChecker_IsAccountVerified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAccountVerified'
type MockUserChecker_IsAccountVerified_Call struct {
	*mock.Call
}

// IsAccountVerified is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockUserChecker_Expecter) IsAccountVerified(ctx interface{}, userID interface{}) *MockUserChecker_IsAccountVerified_Call {
	return &MockUserChecker_IsAccountVerified_Call{Call: _e.mock.On("IsAccountVerified", ctx, userID)}
}

func (_c *MockUserChecker_IsAccountVerified_Call) Run(run func(ctx context.Context, userID uint)) *MockUserChecker_IsAccountVerified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserChecker_IsAccountVerified_Call) Return(b bool, err error) *MockUserChecker_IsAccountVerified_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockUserChecker_IsAccountVerified_Call) RunAndReturn(run func(ctx context.Context, userID uint) (bool, error)) *MockUserChecker_IsAccountVerified_Call {
	_c.Call.Return(run)
	return _c
}
