// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	jwt0 "github.com/golang-jwt/jwt/v5"
	"github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-middleware/auth/jwt"
)

// NewMockJWTKeyLogger creates a new instance of MockJWTKeyLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJWTKeyLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJWTKeyLogger {
	mock := &MockJWTKeyLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJWTKeyLogger is an autogenerated mock type for the JWTKeyLogger type
type MockJWTKeyLogger struct {
	mock.Mock
}

type MockJWTKeyLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJWTKeyLogger) EXPECT() *MockJWTKeyLogger_Expecter {
	return &MockJWTKeyLogger_Expecter{mock: &_m.Mock}
}

// RecordAccess provides a mock function for the type MockJWTKeyLogger
func (_mock *MockJWTKeyLogger) RecordAccess(c echo.Context, token string, purpose jwt.Purpose, claims jwt0.Claims, err error) {
	_mock.Called(c, token, purpose, claims, err)
	return
}

// MockJWTKeyLogger_RecordAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordAccess'
type MockJWTKeyLogger_RecordAccess_Call struct {
	*mock.Call
}

// RecordAccess is a helper method to define mock.On call
//   - c echo.Context
//   - token string
//   - purpose jwt.Purpose
//   - claims jwt0.Claims
//   - err error
func (_e *MockJWTKeyLogger_Expecter) RecordAccess(c any, token any, purpose any, claims any, err any) *MockJWTKeyLogger_RecordAccess_Call {
	return &MockJWTKeyLogger_RecordAccess_Call{Call: _e.mock.On("RecordAccess", c, token, purpose, claims, err)}
}

func (_c *MockJWTKeyLogger_RecordAccess_Call) Run(run func(c echo.Context, token string, purpose jwt.Purpose, claims jwt0.Claims, err error)) *MockJWTKeyLogger_RecordAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 jwt.Purpose
		if args[2] != nil {
			arg2 = args[2].(jwt.Purpose)
		}
		var arg3 jwt0.Claims
		if args[3] != nil {
			arg3 = args[3].(jwt0.Claims)
		}
		var arg4 error
		if args[4] != nil {
			arg4 = args[4].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockJWTKeyLogger_RecordAccess_Call) Return() *MockJWTKeyLogger_RecordAccess_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockJWTKeyLogger_RecordAccess_Call) RunAndReturn(run func(c echo.Context, token string, purpose jwt.Purpose, claims jwt0.Claims, err error)) *MockJWTKeyLogger_RecordAccess_Call {
	_c.Run(run)
	return _c
}
