// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAccessChecker creates a new instance of MockAccessChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccessChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccessChecker {
	mock := &MockAccessChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccessChecker is an autogenerated mock type for the AccessChecker type
type MockAccessChecker struct {
	mock.Mock
}

type MockAccessChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccessChecker) EXPECT() *MockAccessChecker_Expecter {
	return &MockAccessChecker_Expecter{mock: &_m.Mock}
}

// CheckAccess provides a mock function for the type MockAccessChecker
func (_mock *MockAccessChecker) CheckAccess(ctx context.Context, userID uint, host string, path string, method string) (bool, error) {
	ret := _mock.Called(ctx, userID, host, path, method)

	if len(ret) == 0 {
		panic("no return value specified for CheckAccess")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string, string, string) (bool, error)); ok {
		return returnFunc(ctx, userID, host, path, method)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string, string, string) bool); ok {
		r0 = returnFunc(ctx, userID, host, path, method)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, string, string, string) error); ok {
		r1 = returnFunc(ctx, userID, host, path, method)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccessChecker_CheckAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckAccess'
type MockAccessChecker_CheckAccess_Call struct {
	*mock.Call
}

// CheckAccess is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - host string
//   - path string
//   - method string
func (_e *MockAccessChecker_Expecter) CheckAccess(ctx interface{}, userID interface{}, host interface{}, path interface{}, method interface{}) *MockAccessChecker_CheckAccess_Call {
	return &MockAccessChecker_CheckAccess_Call{Call: _e.mock.On("CheckAccess", ctx, userID, host, path, method)}
}

func (_c *MockAccessChecker_CheckAccess_Call) Run(run func(ctx context.Context, userID uint, host string, path string, method string)) *MockAccessChecker_CheckAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockAccessChecker_CheckAccess_Call) Return(b bool, err error) *MockAccessChecker_CheckAccess_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockAccessChecker_CheckAccess_Call) RunAndReturn(run func(ctx context.Context, userID uint, host string, path string, method string) (bool, error)) *MockAccessChecker_CheckAccess_Call {
	_c.Call.Return(run)
	return _c
}
