// Code generated by mockery. DO NOT EDIT.

package auth

import mock "github.com/stretchr/testify/mock"

// MockUserChecker is an autogenerated mock type for the UserChecker type
type MockUserChecker struct {
	mock.Mock
}

type MockUserChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserChecker) EXPECT() *MockUserChecker_Expecter {
	return &MockUserChecker_Expecter{mock: &_m.Mock}
}

// AccountExists provides a mock function with given fields: userID
func (_m *MockUserChecker) AccountExists(userID uint) (bool, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for AccountExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (bool, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint) bool); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserChecker_AccountExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AccountExists'
type MockUserChecker_AccountExists_Call struct {
	*mock.Call
}

// AccountExists is a helper method to define mock.On call
//   - userID uint
func (_e *MockUserChecker_Expecter) AccountExists(userID interface{}) *MockUserChecker_AccountExists_Call {
	return &MockUserChecker_AccountExists_Call{Call: _e.mock.On("AccountExists", userID)}
}

func (_c *MockUserChecker_AccountExists_Call) Run(run func(userID uint)) *MockUserChecker_AccountExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockUserChecker_AccountExists_Call) Return(_a0 bool, _a1 error) *MockUserChecker_AccountExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserChecker_AccountExists_Call) RunAndReturn(run func(uint) (bool, error)) *MockUserChecker_AccountExists_Call {
	_c.Call.Return(run)
	return _c
}

// IsAccountVerified provides a mock function with given fields: userID
func (_m *MockUserChecker) IsAccountVerified(userID uint) (bool, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for IsAccountVerified")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (bool, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint) bool); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserChecker_IsAccountVerified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAccountVerified'
type MockUserChecker_IsAccountVerified_Call struct {
	*mock.Call
}

// IsAccountVerified is a helper method to define mock.On call
//   - userID uint
func (_e *MockUserChecker_Expecter) IsAccountVerified(userID interface{}) *MockUserChecker_IsAccountVerified_Call {
	return &MockUserChecker_IsAccountVerified_Call{Call: _e.mock.On("IsAccountVerified", userID)}
}

func (_c *MockUserChecker_IsAccountVerified_Call) Run(run func(userID uint)) *MockUserChecker_IsAccountVerified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockUserChecker_IsAccountVerified_Call) Return(_a0 bool, _a1 error) *MockUserChecker_IsAccountVerified_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserChecker_IsAccountVerified_Call) RunAndReturn(run func(uint) (bool, error)) *MockUserChecker_IsAccountVerified_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserChecker creates a new instance of MockUserChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserChecker {
	mock := &MockUserChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
