// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package validation

import (
	jwt0 "github.com/golang-jwt/jwt/v5"
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-middleware/auth/jwt"
)

// NewMockTokenValidator creates a new instance of MockTokenValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenValidator {
	mock := &MockTokenValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenValidator is an autogenerated mock type for the TokenValidator type
type MockTokenValidator struct {
	mock.Mock
}

type MockTokenValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenValidator) EXPECT() *MockTokenValidator_Expecter {
	return &MockTokenValidator_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function for the type MockTokenValidator
func (_mock *MockTokenValidator) Validate(token string, purpose jwt.Purpose) (*jwt0.RegisteredClaims, error) {
	ret := _mock.Called(token, purpose)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 *jwt0.RegisteredClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, jwt.Purpose) (*jwt0.RegisteredClaims, error)); ok {
		return returnFunc(token, purpose)
	}
	if returnFunc, ok := ret.Get(0).(func(string, jwt.Purpose) *jwt0.RegisteredClaims); ok {
		r0 = returnFunc(token, purpose)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt0.RegisteredClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, jwt.Purpose) error); ok {
		r1 = returnFunc(token, purpose)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockTokenValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - token string
//   - purpose jwt.Purpose
func (_e *MockTokenValidator_Expecter) Validate(token interface{}, purpose interface{}) *MockTokenValidator_Validate_Call {
	return &MockTokenValidator_Validate_Call{Call: _e.mock.On("Validate", token, purpose)}
}

func (_c *MockTokenValidator_Validate_Call) Run(run func(token string, purpose jwt.Purpose)) *MockTokenValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 jwt.Purpose
		if args[1] != nil {
			arg1 = args[1].(jwt.Purpose)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenValidator_Validate_Call) Return(registeredClaims *jwt0.RegisteredClaims, err error) *MockTokenValidator_Validate_Call {
	_c.Call.Return(registeredClaims, err)
	return _c
}

func (_c *MockTokenValidator_Validate_Call) RunAndReturn(run func(token string, purpose jwt.Purpose) (*jwt0.RegisteredClaims, error)) *MockTokenValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateWithClaims provides a mock function for the type MockTokenValidator
func (_mock *MockTokenValidator) ValidateWithClaims(token string, purpose jwt.Purpose, claimsType jwt0.Claims) (*jwt0.RegisteredClaims, jwt0.Claims, error) {
	ret := _mock.Called(token, purpose, claimsType)

	if len(ret) == 0 {
		panic("no return value specified for ValidateWithClaims")
	}

	var r0 *jwt0.RegisteredClaims
	var r1 jwt0.Claims
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, jwt.Purpose, jwt0.Claims) (*jwt0.RegisteredClaims, jwt0.Claims, error)); ok {
		return returnFunc(token, purpose, claimsType)
	}
	if returnFunc, ok := ret.Get(0).(func(string, jwt.Purpose, jwt0.Claims) *jwt0.RegisteredClaims); ok {
		r0 = returnFunc(token, purpose, claimsType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt0.RegisteredClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, jwt.Purpose, jwt0.Claims) jwt0.Claims); ok {
		r1 = returnFunc(token, purpose, claimsType)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(jwt0.Claims)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(string, jwt.Purpose, jwt0.Claims) error); ok {
		r2 = returnFunc(token, purpose, claimsType)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTokenValidator_ValidateWithClaims_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateWithClaims'
type MockTokenValidator_ValidateWithClaims_Call struct {
	*mock.Call
}

// ValidateWithClaims is a helper method to define mock.On call
//   - token string
//   - purpose jwt.Purpose
//   - claimsType jwt0.Claims
func (_e *MockTokenValidator_Expecter) ValidateWithClaims(token interface{}, purpose interface{}, claimsType interface{}) *MockTokenValidator_ValidateWithClaims_Call {
	return &MockTokenValidator_ValidateWithClaims_Call{Call: _e.mock.On("ValidateWithClaims", token, purpose, claimsType)}
}

func (_c *MockTokenValidator_ValidateWithClaims_Call) Run(run func(token string, purpose jwt.Purpose, claimsType jwt0.Claims)) *MockTokenValidator_ValidateWithClaims_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 jwt.Purpose
		if args[1] != nil {
			arg1 = args[1].(jwt.Purpose)
		}
		var arg2 jwt0.Claims
		if args[2] != nil {
			arg2 = args[2].(jwt0.Claims)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTokenValidator_ValidateWithClaims_Call) Return(registeredClaims *jwt0.RegisteredClaims, claims jwt0.Claims, err error) *MockTokenValidator_ValidateWithClaims_Call {
	_c.Call.Return(registeredClaims, claims, err)
	return _c
}

func (_c *MockTokenValidator_ValidateWithClaims_Call) RunAndReturn(run func(token string, purpose jwt.Purpose, claimsType jwt0.Claims) (*jwt0.RegisteredClaims, jwt0.Claims, error)) *MockTokenValidator_ValidateWithClaims_Call {
	_c.Call.Return(run)
	return _c
}
