// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package adapter

import (
	"net/http"
	"time"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-middleware/auth/jwt"
)

// NewMockCookieSetter creates a new instance of MockCookieSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCookieSetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCookieSetter {
	mock := &MockCookieSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCookieSetter is an autogenerated mock type for the CookieSetter type
type MockCookieSetter struct {
	mock.Mock
}

type MockCookieSetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCookieSetter) EXPECT() *MockCookieSetter_Expecter {
	return &MockCookieSetter_Expecter{mock: &_m.Mock}
}

// ClearJWTCookie provides a mock function for the type MockCookieSetter
func (_mock *MockCookieSetter) ClearJWTCookie(w http.ResponseWriter) {
	_mock.Called(w)
	return
}

// MockCookieSetter_ClearJWTCookie_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearJWTCookie'
type MockCookieSetter_ClearJWTCookie_Call struct {
	*mock.Call
}

// ClearJWTCookie is a helper method to define mock.On call
//   - w http.ResponseWriter
func (_e *MockCookieSetter_Expecter) ClearJWTCookie(w interface{}) *MockCookieSetter_ClearJWTCookie_Call {
	return &MockCookieSetter_ClearJWTCookie_Call{Call: _e.mock.On("ClearJWTCookie", w)}
}

func (_c *MockCookieSetter_ClearJWTCookie_Call) Run(run func(w http.ResponseWriter)) *MockCookieSetter_ClearJWTCookie_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCookieSetter_ClearJWTCookie_Call) Return() *MockCookieSetter_ClearJWTCookie_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCookieSetter_ClearJWTCookie_Call) RunAndReturn(run func(w http.ResponseWriter)) *MockCookieSetter_ClearJWTCookie_Call {
	_c.Run(run)
	return _c
}

// Config provides a mock function for the type MockCookieSetter
func (_mock *MockCookieSetter) Config() ConfigProvider {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 ConfigProvider
	if returnFunc, ok := ret.Get(0).(func() ConfigProvider); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ConfigProvider)
		}
	}
	return r0
}

// MockCookieSetter_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockCookieSetter_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockCookieSetter_Expecter) Config() *MockCookieSetter_Config_Call {
	return &MockCookieSetter_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockCookieSetter_Config_Call) Run(run func()) *MockCookieSetter_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCookieSetter_Config_Call) Return(configProvider ConfigProvider) *MockCookieSetter_Config_Call {
	_c.Call.Return(configProvider)
	return _c
}

func (_c *MockCookieSetter_Config_Call) RunAndReturn(run func() ConfigProvider) *MockCookieSetter_Config_Call {
	_c.Call.Return(run)
	return _c
}

// EchoAuthCookie provides a mock function for the type MockCookieSetter
func (_mock *MockCookieSetter) EchoAuthCookie(w http.ResponseWriter, r *http.Request, opts ...jwt.Option) {
	// jwt.Option
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, w, r)
	_ca = append(_ca, _va...)
	_mock.Called(_ca...)
	return
}

// MockCookieSetter_EchoAuthCookie_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EchoAuthCookie'
type MockCookieSetter_EchoAuthCookie_Call struct {
	*mock.Call
}

// EchoAuthCookie is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
//   - opts ...jwt.Option
func (_e *MockCookieSetter_Expecter) EchoAuthCookie(w interface{}, r interface{}, opts ...interface{}) *MockCookieSetter_EchoAuthCookie_Call {
	return &MockCookieSetter_EchoAuthCookie_Call{Call: _e.mock.On("EchoAuthCookie",
		append([]interface{}{w, r}, opts...)...)}
}

func (_c *MockCookieSetter_EchoAuthCookie_Call) Run(run func(w http.ResponseWriter, r *http.Request, opts ...jwt.Option)) *MockCookieSetter_EchoAuthCookie_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		var arg2 []jwt.Option
		variadicArgs := make([]jwt.Option, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(jwt.Option)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCookieSetter_EchoAuthCookie_Call) Return() *MockCookieSetter_EchoAuthCookie_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCookieSetter_EchoAuthCookie_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request, opts ...jwt.Option)) *MockCookieSetter_EchoAuthCookie_Call {
	_c.Run(run)
	return _c
}

// SetCookie provides a mock function for the type MockCookieSetter
func (_mock *MockCookieSetter) SetCookie(w http.ResponseWriter, name string, value string, domain string, path string, expiry time.Time, secure bool, httpOnly bool, sameSite http.SameSite) {
	_mock.Called(w, name, value, domain, path, expiry, secure, httpOnly, sameSite)
	return
}

// MockCookieSetter_SetCookie_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCookie'
type MockCookieSetter_SetCookie_Call struct {
	*mock.Call
}

// SetCookie is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - name string
//   - value string
//   - domain string
//   - path string
//   - expiry time.Time
//   - secure bool
//   - httpOnly bool
//   - sameSite http.SameSite
func (_e *MockCookieSetter_Expecter) SetCookie(w interface{}, name interface{}, value interface{}, domain interface{}, path interface{}, expiry interface{}, secure interface{}, httpOnly interface{}, sameSite interface{}) *MockCookieSetter_SetCookie_Call {
	return &MockCookieSetter_SetCookie_Call{Call: _e.mock.On("SetCookie", w, name, value, domain, path, expiry, secure, httpOnly, sameSite)}
}

func (_c *MockCookieSetter_SetCookie_Call) Run(run func(w http.ResponseWriter, name string, value string, domain string, path string, expiry time.Time, secure bool, httpOnly bool, sameSite http.SameSite)) *MockCookieSetter_SetCookie_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 time.Time
		if args[5] != nil {
			arg5 = args[5].(time.Time)
		}
		var arg6 bool
		if args[6] != nil {
			arg6 = args[6].(bool)
		}
		var arg7 bool
		if args[7] != nil {
			arg7 = args[7].(bool)
		}
		var arg8 http.SameSite
		if args[8] != nil {
			arg8 = args[8].(http.SameSite)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
			arg8,
		)
	})
	return _c
}

func (_c *MockCookieSetter_SetCookie_Call) Return() *MockCookieSetter_SetCookie_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCookieSetter_SetCookie_Call) RunAndReturn(run func(w http.ResponseWriter, name string, value string, domain string, path string, expiry time.Time, secure bool, httpOnly bool, sameSite http.SameSite)) *MockCookieSetter_SetCookie_Call {
	_c.Run(run)
	return _c
}

// SetJWTCookie provides a mock function for the type MockCookieSetter
func (_mock *MockCookieSetter) SetJWTCookie(w http.ResponseWriter, subject string, purpose jwt.Purpose, expiry time.Duration, opts ...jwt.Option) (string, error) {
	// jwt.Option
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, w, subject, purpose, expiry)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SetJWTCookie")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(http.ResponseWriter, string, jwt.Purpose, time.Duration, ...jwt.Option) (string, error)); ok {
		return returnFunc(w, subject, purpose, expiry, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(http.ResponseWriter, string, jwt.Purpose, time.Duration, ...jwt.Option) string); ok {
		r0 = returnFunc(w, subject, purpose, expiry, opts...)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(http.ResponseWriter, string, jwt.Purpose, time.Duration, ...jwt.Option) error); ok {
		r1 = returnFunc(w, subject, purpose, expiry, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCookieSetter_SetJWTCookie_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetJWTCookie'
type MockCookieSetter_SetJWTCookie_Call struct {
	*mock.Call
}

// SetJWTCookie is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - subject string
//   - purpose jwt.Purpose
//   - expiry time.Duration
//   - opts ...jwt.Option
func (_e *MockCookieSetter_Expecter) SetJWTCookie(w interface{}, subject interface{}, purpose interface{}, expiry interface{}, opts ...interface{}) *MockCookieSetter_SetJWTCookie_Call {
	return &MockCookieSetter_SetJWTCookie_Call{Call: _e.mock.On("SetJWTCookie",
		append([]interface{}{w, subject, purpose, expiry}, opts...)...)}
}

func (_c *MockCookieSetter_SetJWTCookie_Call) Run(run func(w http.ResponseWriter, subject string, purpose jwt.Purpose, expiry time.Duration, opts ...jwt.Option)) *MockCookieSetter_SetJWTCookie_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 jwt.Purpose
		if args[2] != nil {
			arg2 = args[2].(jwt.Purpose)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		var arg4 []jwt.Option
		variadicArgs := make([]jwt.Option, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(jwt.Option)
			}
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *MockCookieSetter_SetJWTCookie_Call) Return(s string, err error) *MockCookieSetter_SetJWTCookie_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockCookieSetter_SetJWTCookie_Call) RunAndReturn(run func(w http.ResponseWriter, subject string, purpose jwt.Purpose, expiry time.Duration, opts ...jwt.Option) (string, error)) *MockCookieSetter_SetJWTCookie_Call {
	_c.Call.Return(run)
	return _c
}
