// Code generated by mockery. DO NOT EDIT.

package adapter

import (
	ed25519 "crypto/ed25519"

	mock "github.com/stretchr/testify/mock"
)

// MockConfigProvider is an autogenerated mock type for the ConfigProvider type
type MockConfigProvider struct {
	mock.Mock
}

type MockConfigProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigProvider) EXPECT() *MockConfigProvider_Expecter {
	return &MockConfigProvider_Expecter{mock: &_m.Mock}
}

// GetAuthCookieName provides a mock function with no fields
func (_m *MockConfigProvider) GetAuthCookieName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAuthCookieName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockConfigProvider_GetAuthCookieName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthCookieName'
type MockConfigProvider_GetAuthCookieName_Call struct {
	*mock.Call
}

// GetAuthCookieName is a helper method to define mock.On call
func (_e *MockConfigProvider_Expecter) GetAuthCookieName() *MockConfigProvider_GetAuthCookieName_Call {
	return &MockConfigProvider_GetAuthCookieName_Call{Call: _e.mock.On("GetAuthCookieName")}
}

func (_c *MockConfigProvider_GetAuthCookieName_Call) Run(run func()) *MockConfigProvider_GetAuthCookieName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigProvider_GetAuthCookieName_Call) Return(_a0 string) *MockConfigProvider_GetAuthCookieName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigProvider_GetAuthCookieName_Call) RunAndReturn(run func() string) *MockConfigProvider_GetAuthCookieName_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthTokenName provides a mock function with no fields
func (_m *MockConfigProvider) GetAuthTokenName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAuthTokenName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockConfigProvider_GetAuthTokenName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthTokenName'
type MockConfigProvider_GetAuthTokenName_Call struct {
	*mock.Call
}

// GetAuthTokenName is a helper method to define mock.On call
func (_e *MockConfigProvider_Expecter) GetAuthTokenName() *MockConfigProvider_GetAuthTokenName_Call {
	return &MockConfigProvider_GetAuthTokenName_Call{Call: _e.mock.On("GetAuthTokenName")}
}

func (_c *MockConfigProvider_GetAuthTokenName_Call) Run(run func()) *MockConfigProvider_GetAuthTokenName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigProvider_GetAuthTokenName_Call) Return(_a0 string) *MockConfigProvider_GetAuthTokenName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigProvider_GetAuthTokenName_Call) RunAndReturn(run func() string) *MockConfigProvider_GetAuthTokenName_Call {
	_c.Call.Return(run)
	return _c
}

// GetDomain provides a mock function with no fields
func (_m *MockConfigProvider) GetDomain() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDomain")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockConfigProvider_GetDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDomain'
type MockConfigProvider_GetDomain_Call struct {
	*mock.Call
}

// GetDomain is a helper method to define mock.On call
func (_e *MockConfigProvider_Expecter) GetDomain() *MockConfigProvider_GetDomain_Call {
	return &MockConfigProvider_GetDomain_Call{Call: _e.mock.On("GetDomain")}
}

func (_c *MockConfigProvider_GetDomain_Call) Run(run func()) *MockConfigProvider_GetDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigProvider_GetDomain_Call) Return(_a0 string) *MockConfigProvider_GetDomain_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigProvider_GetDomain_Call) RunAndReturn(run func() string) *MockConfigProvider_GetDomain_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrivateKey provides a mock function with no fields
func (_m *MockConfigProvider) GetPrivateKey() ed25519.PrivateKey {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPrivateKey")
	}

	var r0 ed25519.PrivateKey
	if rf, ok := ret.Get(0).(func() ed25519.PrivateKey); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ed25519.PrivateKey)
		}
	}

	return r0
}

// MockConfigProvider_GetPrivateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrivateKey'
type MockConfigProvider_GetPrivateKey_Call struct {
	*mock.Call
}

// GetPrivateKey is a helper method to define mock.On call
func (_e *MockConfigProvider_Expecter) GetPrivateKey() *MockConfigProvider_GetPrivateKey_Call {
	return &MockConfigProvider_GetPrivateKey_Call{Call: _e.mock.On("GetPrivateKey")}
}

func (_c *MockConfigProvider_GetPrivateKey_Call) Run(run func()) *MockConfigProvider_GetPrivateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigProvider_GetPrivateKey_Call) Return(_a0 ed25519.PrivateKey) *MockConfigProvider_GetPrivateKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigProvider_GetPrivateKey_Call) RunAndReturn(run func() ed25519.PrivateKey) *MockConfigProvider_GetPrivateKey_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConfigProvider creates a new instance of MockConfigProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigProvider {
	mock := &MockConfigProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
