// Code generated by mockery v2.53.3. DO NOT EDIT.

package auth

import mock "github.com/stretchr/testify/mock"

// MockAPIProvider is an autogenerated mock type for the APIProvider type
type MockAPIProvider struct {
	mock.Mock
}

type MockAPIProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIProvider) EXPECT() *MockAPIProvider_Expecter {
	return &MockAPIProvider_Expecter{mock: &_m.Mock}
}

// GetAPIs provides a mock function with no fields
func (_m *MockAPIProvider) GetAPIs() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAPIs")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockAPIProvider_GetAPIs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAPIs'
type MockAPIProvider_GetAPIs_Call struct {
	*mock.Call
}

// GetAPIs is a helper method to define mock.On call
func (_e *MockAPIProvider_Expecter) GetAPIs() *MockAPIProvider_GetAPIs_Call {
	return &MockAPIProvider_GetAPIs_Call{Call: _e.mock.On("GetAPIs")}
}

func (_c *MockAPIProvider_GetAPIs_Call) Run(run func()) *MockAPIProvider_GetAPIs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAPIProvider_GetAPIs_Call) Return(_a0 []string) *MockAPIProvider_GetAPIs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAPIProvider_GetAPIs_Call) RunAndReturn(run func() []string) *MockAPIProvider_GetAPIs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAPIProvider creates a new instance of MockAPIProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIProvider {
	mock := &MockAPIProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
