// Code generated by mockery v2.53.3. DO NOT EDIT.

package auth

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
	jwt "go.lumeweb.com/portal-middleware/auth/jwt"

	time "time"
)

// MockCookieSetter is an autogenerated mock type for the CookieSetter type
type MockCookieSetter struct {
	mock.Mock
}

type MockCookieSetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCookieSetter) EXPECT() *MockCookieSetter_Expecter {
	return &MockCookieSetter_Expecter{mock: &_m.Mock}
}

// ClearJWTCookie provides a mock function with given fields: w
func (_m *MockCookieSetter) ClearJWTCookie(w http.ResponseWriter) {
	_m.Called(w)
}

// MockCookieSetter_ClearJWTCookie_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearJWTCookie'
type MockCookieSetter_ClearJWTCookie_Call struct {
	*mock.Call
}

// ClearJWTCookie is a helper method to define mock.On call
//   - w http.ResponseWriter
func (_e *MockCookieSetter_Expecter) ClearJWTCookie(w interface{}) *MockCookieSetter_ClearJWTCookie_Call {
	return &MockCookieSetter_ClearJWTCookie_Call{Call: _e.mock.On("ClearJWTCookie", w)}
}

func (_c *MockCookieSetter_ClearJWTCookie_Call) Run(run func(w http.ResponseWriter)) *MockCookieSetter_ClearJWTCookie_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter))
	})
	return _c
}

func (_c *MockCookieSetter_ClearJWTCookie_Call) Return() *MockCookieSetter_ClearJWTCookie_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCookieSetter_ClearJWTCookie_Call) RunAndReturn(run func(http.ResponseWriter)) *MockCookieSetter_ClearJWTCookie_Call {
	_c.Run(run)
	return _c
}

// SetJWTCookie provides a mock function with given fields: w, subject, purpose, expiry
func (_m *MockCookieSetter) SetJWTCookie(w http.ResponseWriter, subject string, purpose jwt.JWTPurpose, expiry time.Duration) (string, error) {
	ret := _m.Called(w, subject, purpose, expiry)

	if len(ret) == 0 {
		panic("no return value specified for SetJWTCookie")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(http.ResponseWriter, string, jwt.JWTPurpose, time.Duration) (string, error)); ok {
		return rf(w, subject, purpose, expiry)
	}
	if rf, ok := ret.Get(0).(func(http.ResponseWriter, string, jwt.JWTPurpose, time.Duration) string); ok {
		r0 = rf(w, subject, purpose, expiry)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(http.ResponseWriter, string, jwt.JWTPurpose, time.Duration) error); ok {
		r1 = rf(w, subject, purpose, expiry)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCookieSetter_SetJWTCookie_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetJWTCookie'
type MockCookieSetter_SetJWTCookie_Call struct {
	*mock.Call
}

// SetJWTCookie is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - subject string
//   - purpose jwt.JWTPurpose
//   - expiry time.Duration
func (_e *MockCookieSetter_Expecter) SetJWTCookie(w interface{}, subject interface{}, purpose interface{}, expiry interface{}) *MockCookieSetter_SetJWTCookie_Call {
	return &MockCookieSetter_SetJWTCookie_Call{Call: _e.mock.On("SetJWTCookie", w, subject, purpose, expiry)}
}

func (_c *MockCookieSetter_SetJWTCookie_Call) Run(run func(w http.ResponseWriter, subject string, purpose jwt.JWTPurpose, expiry time.Duration)) *MockCookieSetter_SetJWTCookie_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(string), args[2].(jwt.JWTPurpose), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockCookieSetter_SetJWTCookie_Call) Return(_a0 string, _a1 error) *MockCookieSetter_SetJWTCookie_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCookieSetter_SetJWTCookie_Call) RunAndReturn(run func(http.ResponseWriter, string, jwt.JWTPurpose, time.Duration) (string, error)) *MockCookieSetter_SetJWTCookie_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCookieSetter creates a new instance of MockCookieSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCookieSetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCookieSetter {
	mock := &MockCookieSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
