// Code generated by mockery v2.53.3. DO NOT EDIT.

package auth

import (
	jwt "github.com/golang-jwt/jwt/v5"
	mock "github.com/stretchr/testify/mock"
)

// MockTokenValidator is an autogenerated mock type for the TokenValidator type
type MockTokenValidator struct {
	mock.Mock
}

type MockTokenValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenValidator) EXPECT() *MockTokenValidator_Expecter {
	return &MockTokenValidator_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function with given fields: token, purpose
func (_m *MockTokenValidator) Validate(token string, purpose string) (*jwt.RegisteredClaims, error) {
	ret := _m.Called(token, purpose)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 *jwt.RegisteredClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*jwt.RegisteredClaims, error)); ok {
		return rf(token, purpose)
	}
	if rf, ok := ret.Get(0).(func(string, string) *jwt.RegisteredClaims); ok {
		r0 = rf(token, purpose)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.RegisteredClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(token, purpose)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockTokenValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - token string
//   - purpose string
func (_e *MockTokenValidator_Expecter) Validate(token interface{}, purpose interface{}) *MockTokenValidator_Validate_Call {
	return &MockTokenValidator_Validate_Call{Call: _e.mock.On("Validate", token, purpose)}
}

func (_c *MockTokenValidator_Validate_Call) Run(run func(token string, purpose string)) *MockTokenValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockTokenValidator_Validate_Call) Return(_a0 *jwt.RegisteredClaims, _a1 error) *MockTokenValidator_Validate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenValidator_Validate_Call) RunAndReturn(run func(string, string) (*jwt.RegisteredClaims, error)) *MockTokenValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateWithClaims provides a mock function with given fields: token, purpose
func (_m *MockTokenValidator) ValidateWithClaims(token string, purpose string) (*jwt.RegisteredClaims, map[interface{}]interface{}, error) {
	ret := _m.Called(token, purpose)

	if len(ret) == 0 {
		panic("no return value specified for ValidateWithClaims")
	}

	var r0 *jwt.RegisteredClaims
	var r1 map[interface{}]interface{}
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string) (*jwt.RegisteredClaims, map[interface{}]interface{}, error)); ok {
		return rf(token, purpose)
	}
	if rf, ok := ret.Get(0).(func(string, string) *jwt.RegisteredClaims); ok {
		r0 = rf(token, purpose)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.RegisteredClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) map[interface{}]interface{}); ok {
		r1 = rf(token, purpose)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[interface{}]interface{})
		}
	}

	if rf, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = rf(token, purpose)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTokenValidator_ValidateWithClaims_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateWithClaims'
type MockTokenValidator_ValidateWithClaims_Call struct {
	*mock.Call
}

// ValidateWithClaims is a helper method to define mock.On call
//   - token string
//   - purpose string
func (_e *MockTokenValidator_Expecter) ValidateWithClaims(token interface{}, purpose interface{}) *MockTokenValidator_ValidateWithClaims_Call {
	return &MockTokenValidator_ValidateWithClaims_Call{Call: _e.mock.On("ValidateWithClaims", token, purpose)}
}

func (_c *MockTokenValidator_ValidateWithClaims_Call) Run(run func(token string, purpose string)) *MockTokenValidator_ValidateWithClaims_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockTokenValidator_ValidateWithClaims_Call) Return(_a0 *jwt.RegisteredClaims, _a1 map[interface{}]interface{}, _a2 error) *MockTokenValidator_ValidateWithClaims_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockTokenValidator_ValidateWithClaims_Call) RunAndReturn(run func(string, string) (*jwt.RegisteredClaims, map[interface{}]interface{}, error)) *MockTokenValidator_ValidateWithClaims_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenValidator creates a new instance of MockTokenValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenValidator {
	mock := &MockTokenValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
